# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gee-polygons',
                'doc_host': 'https://aliceheiman.github.io',
                'git_url': 'https://github.com/aliceheiman/gee-polygons',
                'lib_path': 'gee_polygons'},
  'syms': {'gee_polygons.core': {'gee_polygons.core.foo': ('core.html#foo', 'gee_polygons/core.py')}}}
