"""Pure configuration objects for describing categorical raster layers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_layers.ipynb.

# %% auto #0
__all__ = ['CategoricalLayer']

# %% ../nbs/00_layers.ipynb #e85412d5
from dataclasses import dataclass, field
from typing import Optional, Dict

# %% ../nbs/00_layers.ipynb #06fdbff1
@dataclass
class CategoricalLayer:
    """A descriptor for a categorical raster layer with annual bands.
    
    This is a pure configuration object — no GEE calls, no logic.
    
    Attributes:
        asset_id: GEE asset path (e.g., 'projects/mapbiomas-public/assets/...')
        band_pattern: Pattern for yearly bands with {} placeholder (e.g., 'classification_{}')
        scale: Pixel resolution in meters (default 30)
        class_map: Optional mapping of class values to names
        palette: Optional mapping of class values to hex colors
    """
    asset_id: str
    band_pattern: str
    scale: int = 30
    class_map: Optional[Dict[int, str]] = None
    palette: Optional[Dict[int, str]] = None
    
    def band_name(self, year: int) -> str:
        """Get the band name for a specific year."""
        return self.band_pattern.format(year)
    
    def class_name(self, class_value: int) -> Optional[str]:
        """Get the human-readable name for a class value."""
        if self.class_map is None:
            return None
        return self.class_map.get(class_value)
    
    def class_color(self, class_value: int) -> Optional[str]:
        """Get the hex color for a class value."""
        if self.palette is None:
            return None
        return self.palette.get(class_value)
